In [8]:
import numpy as np



a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
             [4,5,6,7]])
d = np.zeros((2,4))
e = np.random.rand(2,5)



print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5470875  0.72256091 0.52926769 0.70953835 0.79135392]
 [0.00221999 0.94914075 0.74541294 0.08947101 0.77016306]]
